15 maj 2025 16:23:01Could not reach inventory database
se.kth.iv1350.pointofsale.controller.SystemOperationFailureException: Could not reach inventory database
	at se.kth.iv1350.pointofsale.controller.Controller.scanItem(Controller.java:71)
	at se.kth.iv1350.pointofsale.view.View.scanItem(View.java:65)
	at se.kth.iv1350.pointofsale.view.View.runHardcodedSaleProcess(View.java:49)
	at se.kth.iv1350.pointofsale.startup.Main.main(Main.java:37)
Caused by: se.kth.iv1350.pointofsale.integration.DataBaseFailureException: Inventory database can't be reached, check connection and try again...
	at se.kth.iv1350.pointofsale.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:44)
	at se.kth.iv1350.pointofsale.controller.Controller.scanItem(Controller.java:67)
	... 3 more
15 maj 2025 17:31:21Could not reach inventory database
se.kth.iv1350.pointofsale.controller.SystemOperationFailureException: Could not reach inventory database
	at se.kth.iv1350.pointofsale.controller.Controller.scanItem(Controller.java:71)
	at se.kth.iv1350.pointofsale.view.View.scanItem(View.java:65)
	at se.kth.iv1350.pointofsale.view.View.runHardcodedSaleProcess(View.java:49)
	at se.kth.iv1350.pointofsale.startup.Main.main(Main.java:37)
Caused by: se.kth.iv1350.pointofsale.integration.DataBaseFailureException: Inventory database can't be reached, check connection and try again...
	at se.kth.iv1350.pointofsale.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:44)
	at se.kth.iv1350.pointofsale.controller.Controller.scanItem(Controller.java:67)
	... 3 more
